
services:
  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://stockuser:stockpass@postgres:5432/stockdb
      - REDIS_URL=redis://redis:6379
      - ANGEL_API_KEY=sWspiKMS
      - ANGEL_CLIENT_ID=P59977856
      - ANGEL_PASSWORD=3010
      - ANGEL_TOTP_SECRET=WE2VO3P5PCRPOACOVHUS7BKZFE
      - ALPHAVANTAGE_API_KEY=YQKILNW2LG827ITH
      - NEWS_API_KEY=11a5f18a5f844c359947720e5c55f802
      - OPENAI_API_KEY=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
      - SECRET_KEY=$(openssl rand -base64 32)
      - JWT_SECRET_KEY=$(openssl rand -base64 32)
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
      - ./backend/models:/app/models
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - stock-network

  # Frontend React Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - stock-network

  # PostgreSQL Database
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=stock_prediction
      - POSTGRES_USER=stockuser
      - POSTGRES_PASSWORD=$(openssl rand -base64 32)
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - stock-network

  # Redis for caching and session management
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - stock-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - stock-network

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    restart: unless-stopped
    networks:
      - stock-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Dvl@12345
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - stock-network

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  stock-network:
    driver: bridge